### ISSUE TITLE
Not Working with Laravel 9 & Php 8

### ISSUE THREAD

**Issue by hoRacy** [laravel-notification-channels/smsapi#20]
Hi,
Please update package to work with Laravel 9 & PHP 8.
Possible solution:
composer.json (...)
    "require": {
        "php": ">=7.2",
        "illuminate/notifications": "~6.0 || ~7.0 || ~8.0 || ~9.0",
        "illuminate/support": "~6.0 || ~7.0 || ~8.0 || ~9.0",
        "smsapi/php-client": "^1.8"
    },

**Comment by gorczakw** [comment]
#21

**Comment by hoRacy** [comment]
Hello.
@atymic @pxlrbt Is there any chance to merge pull request with L9 to main repo? 

https://github.com/laravel-notification-channels/smsapi/pull/21

Laravel 10 is coming soon ;)

**Comment by pxlrbt** [comment]
@hoRacy I don't have any rights on this repo. I just contributed to that package in the past 😅

**Comment by imrodrigoalves** [comment]
@mdrost @atymic  Can the master version be tagged ?

**Comment by atymic** [comment]
Tagged

**Comment by pxlrbt** [comment]
Thanks guys
