### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by mathishuettl** [laravel-notification-channels/smsapi#3]
Hello,

I always get the error "Authorization failed" even when i try with api-token or with password.
I use the token from here: https://imgur.com/hnHZwyE

- added the provider to config/app.php
- published the config

config/smsapi.php
```
'auth' => [
	'method' => 'token',

	'credentials' => [
		'token' => env('SMSAPI_AUTH_TOKEN'),
	],
```

- added this line to .env file
SMSAPI_AUTH_TOKEN=b0ixlNxxxxxxxxxxxUJkHR1E

**Comment by mdrost** [comment]
Hi, because of http://laravel-notification-channels.com/ being almost dead I forgot a little about this package. Can you try fork from https://github.com/pixwell-dev/smsapi ? Just add to your `composer.json`
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/pixwell-dev/smsapi"
        }
    ]
```

**Comment by mathishuettl** [comment]
hey, sorry i don't unterstand what you mean? Where should i add this to my composer.json? 
https://pastebin.com/cdHjqzz5

And this solves the problem?

**Comment by mdrost** [comment]
Add it before `"require": {`. I don't know if that will solve the problem but I know that currently that fork is more stable until I copy some of their fixes to this repo. Maybe will solve, maybe not... it will not hurt to try.

**Comment by mathishuettl** [comment]
Like that: https://pastebin.com/Q5GvdThD ?
Does i need to run something like composer install or something?
