### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/smsapi#4]
Hi @mdrost 

Are you still interested in maintaining this package?

If so, could we add support for laravel 5.5+ and 6.0?

Thanks!

**Comment by atymic** [comment]
ping @mdrost

**Comment by mdrost** [comment]
Hi @atymic
Currently I am no longer working with PHP and Smsapi. Until someone paid me to do that :P
If you want you can appoint new maintainer. Occasionally I can briefly review and accept pull requests.

**Comment by atymic** [comment]
No worries, thanks for the heads up!

**Comment by atymic** [comment]
Hey @danieljaniga @mathishuettl 
I noticed you have a maintained fork here:
https://github.com/pixwell-dev/smsapi

I was wondering if you'd like to take over maintenance of this package?

Thanks!

**Comment by atymic** [comment]
I'll close this for now as I'll look after it for the time being. If you'd like to become the admin for this package let me know.

**Comment by mdrost** [comment]
Maybe @pxlrbt will be interested with his new pull requests? :P

**Comment by pxlrbt** [comment]
@mdrost @atymic 
I am currently working on a project using SMSAPIs sms functionality. But for now this is only a single project which will be done in fall. Also I am not using mms/vms features.
I happily help with some contributions but I am not sure whether I would be a fitting maintainer.
